[default]
# openai gemini moonshot (月之暗面) oneapi g4f azure qwen (通义千问)   
llm_provider="openai"
base_url=""
model_name=""
api_version=""
# Subtitle Provider, "edge" or "whisper"
subtitle_provider = "edge"
# imagemagick_path = "C:\\Program Files (x86)\\ImageMagick-7.1.1-Q16\\magick.exe"
# ffmpeg_path = "C:\\Users\\harry\\Downloads\\ffmpeg.exe"
# 当视频生成成功后，API服务提供的视频下载接入点，默认为当前服务的地址和监听端口
endpoint=""
enable_redis = false
redis_host = "localhost"
redis_port = 6379
redis_db = 0
redis_password = ""
max_concurrent_tasks = 5
hide_config = false
reload_debug=false

[video]
video_source = "pexels"  # "pexels" or "pixabay"
pexels_api_keys = ""
pixabay_api_keys = ""


[whisper]
# recommended model_size: "large-v3"
model_size="large-v3"
# if you want to use GPU, set device="cuda"
device="CPU"
compute_type="int8"


[proxy]
### Use a proxy to access the Pexels API
# https = "http://10.10.1.10:1080"

[azure]
# Azure Speech API Key
# Get your API key at https://portal.azure.com/#view/Microsoft_Azure_ProjectOxford/CognitiveServicesHub/~/SpeechServices
speech_key=""
speech_region=""
